name: Docker Image CI

on:
  push:
    branches: [ deploy ]
  pull_request:
    branches: [ deploy ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag inmetbot:$(date +%s)
